init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd --quiet verify
clone_depth: 1
test: off
deploy: off
# See http://www.appveyor.com/docs/services-databases#sql-server-2014
services:
  - mssql2014
environment:
  Test__SqlServer__DataSource: (local)\SQL2014
  Test__SqlServer__UserId: sa
  Test__SqlServer__Password: Password12!
  Test__SqlServer__IntegratedSecurity: false
